language: python
matrix:
  include:
    - python: 2.7
      env: KERAS_BACKEND=tensorflow
    - python: 3.5
      env: KERAS_BACKEND=tensorflow
    - python: 3.6
      env: KERAS_BACKEND=tensorflow
# command to install dependencies
install:
  - pip install tensorflow keras
  - pip install coverage
  - pip install pytest-cov
  - pip install codecov
  - pip install -e .[tests]
# command to run tests
script:
  - python -c "import keras.backend"
  - sed -i -e 's/"backend":[[:space:]]*"[^"]*/"backend":\ "'$KERAS_BACKEND'/g' ~/.keras/keras.json;
  - echo -e "Running tests with the following config:\n$(cat ~/.keras/keras.json)"
  - py.test tests/ --cov=pyshac tests/
after_success:
  - codecov
notifications:
  email:
    on_success: never
    on_failure: always
