site_name: PySHAC Documentation
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'light blue'
  search:
    language: 'en'
  feature:
    tabs: false
docs_dir: docs/sources
repo_name: 'titu1994/pyshac'
repo_url: https://github.com/titu1994/pyshac
# site_url: # TODO
site_description: 'Documentation for PySHAC, the Python library for Sequential Halving and Classification.'

dev_addr: '0.0.0.0:8000'
google_analytics:
  - 'UA-47921241-1'
  - 'auto'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.superfences

pages:
- Home: index.md
- Installation: install.md
- User Guide: guide.md
- Serial Evaluation: serial-execution.md
- Managed Engines: managed.md
- Custom Hyper Parameters: custom-hyper-parameters.md
- Config:
  - Hyper Parameters: config/hyperparameters.md
  - Datasets: config/data.md
- Core:
  - SHAC: core/engine.md
  - PyTorch SHAC: core/torch_engine.md
  - Tensorflow SHAC: core/tf_engine.md
  - Keras SHAC: core/keras_engine.md
